export const TEAMS = {
  om: { short: "OM" },
  psg: { short: "PSG" },
  lyon: { short: "OL" },
  monaco: { short: "ASM" },
  barca: { short: "FCB" },
  real: { short: "RMA" },
  milan: { short: "ACM" },
  inter: { short: "INT" },
  juve: { short: "JUV" },
  manutd: { short: "MU" },
  arsenal: { short: "ARS" },
  chelsea: { short: "CHE" },
  liverpool: { short: "LIV" },
  bayern: { short: "BAY" },
  france: { short: "FRA" },
  brazil: { short: "BRE" },
  argentina: { short: "ARG" },
  spain: { short: "ESP" },
  italy: { short: "ITA" },
  germany: { short: "ALL" },
  netherlands: { short: "PB" },
  portugal: { short: "POR" },
  africa: { short: "AFR" }
};

export const CATEGORIES = [
  { id: "om", kicker: "A joué à", title: "l’OM", tags: ["om"], logo: "om" },
  { id: "psg", kicker: "A joué au", title: "PSG", tags: ["psg"], logo: "psg" },
  { id: "lyon", kicker: "A joué à", title: "Lyon", tags: ["lyon"], logo: "lyon" },
  { id: "monaco", kicker: "A joué à", title: "Monaco", tags: ["monaco"], logo: "monaco" },
  { id: "ligue1", kicker: "A joué en", title: "Ligue 1", tags: ["ligue1"], logo: "france" },
  { id: "premierleague", kicker: "A joué en", title: "Premier League", tags: ["premierleague"] },
  { id: "laliga", kicker: "A joué en", title: "Liga", tags: ["laliga"], logo: "spain" },
  { id: "seriea", kicker: "A joué en", title: "Serie A", tags: ["seriea"], logo: "italy" },
  { id: "bundesliga", kicker: "A joué en", title: "Bundesliga", tags: ["bundesliga"], logo: "germany" },
  { id: "barca", kicker: "A joué au", title: "Barça", tags: ["barca"], logo: "barca" },
  { id: "real", kicker: "A joué au", title: "Real Madrid", tags: ["real"], logo: "real" },
  { id: "milan", kicker: "A joué à", title: "l’AC Milan", tags: ["milan"], logo: "milan" },
  { id: "inter", kicker: "A joué à", title: "l’Inter", tags: ["inter"], logo: "inter" },
  { id: "juve", kicker: "A joué à la", title: "Juventus", tags: ["juve"], logo: "juve" },
  { id: "manutd", kicker: "A joué à", title: "Manchester United", tags: ["manutd"], logo: "manutd" },
  { id: "arsenal", kicker: "A joué à", title: "Arsenal", tags: ["arsenal"], logo: "arsenal" },
  { id: "chelsea", kicker: "A joué à", title: "Chelsea", tags: ["chelsea"], logo: "chelsea" },
  { id: "liverpool", kicker: "A joué à", title: "Liverpool", tags: ["liverpool"], logo: "liverpool" },
  { id: "bayern", kicker: "A joué au", title: "Bayern", tags: ["bayern"], logo: "bayern" },
  { id: "uclwinner", kicker: "A gagné", title: "la LDC", tags: ["uclwinner"] },
  { id: "worldcupwinner", kicker: "Champion", title: "du monde", tags: ["worldcupwinner"] },
  { id: "eurowinner", kicker: "A gagné", title: "l’Euro", tags: ["eurowinner"] },
  { id: "ballondor", kicker: "A gagné le", title: "Ballon d’Or", tags: ["ballondor"] },
  { id: "brazil", kicker: "Nationalité", title: "Brésil", tags: ["brazil"], logo: "brazil" },
  { id: "france", kicker: "Nationalité", title: "France", tags: ["france"], logo: "france" },
  { id: "argentina", kicker: "Nationalité", title: "Argentine", tags: ["argentina"], logo: "argentina" },
  { id: "africa", kicker: "Origine", title: "Afrique", tags: ["africa"], logo: "africa" },
  { id: "spain", kicker: "Nationalité", title: "Espagne", tags: ["spain"], logo: "spain" },
  { id: "italy", kicker: "Nationalité", title: "Italie", tags: ["italy"], logo: "italy" },
  { id: "germany", kicker: "Nationalité", title: "Allemagne", tags: ["germany"], logo: "germany" },
  { id: "netherlands", kicker: "Nationalité", title: "Pays-Bas", tags: ["netherlands"], logo: "netherlands" },
  { id: "portugal", kicker: "Nationalité", title: "Portugal", tags: ["portugal"], logo: "portugal" },
  { id: "striker", kicker: "Poste", title: "Attaquant", tags: ["striker"] },
  { id: "midfielder", kicker: "Poste", title: "Milieu", tags: ["midfielder"] },
  { id: "defender", kicker: "Poste", title: "Défenseur", tags: ["defender"] },
  { id: "goalkeeper", kicker: "Poste", title: "Gardien", tags: ["goalkeeper"] },
  { id: "retired", kicker: "Statut", title: "Retraité", tags: ["retired"] },
  { id: "active", kicker: "Statut", title: "En activité", tags: ["active"] },
  { id: "hundredgoals", kicker: "A marqué", title: "+100 buts", tags: ["hundredgoals"] },
  { id: "leftfoot", kicker: "Pied fort", title: "Gaucher", tags: ["leftfoot"] }
];

export const PLAYERS = [
  { id: "zidane", name: "Zinédine Zidane", logos: ["france", "real", "juve"], tags: ["france","worldcupwinner","eurowinner","ballondor","laliga","seriea","real","juve","midfielder","retired"] },
  { id: "ronaldo9", name: "Ronaldo Nazário", logos: ["brazil", "barca", "real", "inter", "milan"], tags: ["brazil","worldcupwinner","ballondor","barca","real","inter","milan","laliga","seriea","striker","retired","hundredgoals"] },
  { id: "ronaldinho", name: "Ronaldinho", logos: ["brazil", "psg", "barca", "milan"], tags: ["brazil","worldcupwinner","ballondor","barca","milan","laliga","seriea","ligue1","psg","midfielder","retired","hundredgoals","uclwinner"] },
  { id: "messi", name: "Lionel Messi", logos: ["argentina", "barca", "psg"], tags: ["argentina","worldcupwinner","ballondor","barca","psg","laliga","ligue1","striker","active","leftfoot","hundredgoals","uclwinner"] },
  { id: "cristiano", name: "Cristiano Ronaldo", logos: ["portugal", "manutd", "real", "juve"], tags: ["portugal","ballondor","manutd","real","juve","premierleague","laliga","seriea","striker","active","hundredgoals","uclwinner"] },
  { id: "benzema", name: "Karim Benzema", logos: ["france", "lyon", "real"], tags: ["france","lyon","ligue1","real","laliga","ballondor","striker","active","hundredgoals","uclwinner"] },
  { id: "mbappe", name: "Kylian Mbappé", logos: ["france", "monaco", "psg", "real"], tags: ["france","worldcupwinner","monaco","psg","real","ligue1","laliga","striker","active","hundredgoals"] },
  { id: "neymar", name: "Neymar", logos: ["brazil", "barca", "psg"], tags: ["brazil","barca","psg","laliga","ligue1","striker","active","hundredgoals","uclwinner"] },
  { id: "henry", name: "Thierry Henry", logos: ["france", "monaco", "arsenal", "barca"], tags: ["france","worldcupwinner","eurowinner","monaco","arsenal","barca","ligue1","premierleague","laliga","striker","retired","hundredgoals","uclwinner"] },
  { id: "drogba", name: "Didier Drogba", logos: ["africa", "om", "chelsea"], tags: ["africa","om","ligue1","chelsea","premierleague","striker","retired","hundredgoals","uclwinner"] },
  { id: "ibrahimovic", name: "Zlatan Ibrahimović", logos: ["psg", "milan", "inter", "juve", "barca"], tags: ["psg","milan","inter","juve","barca","ligue1","seriea","laliga","striker","retired","hundredgoals"] },
  { id: "cavani", name: "Edinson Cavani", logos: ["psg", "manutd"], tags: ["psg","manutd","ligue1","seriea","premierleague","striker","retired","hundredgoals"] },
  { id: "papin", name: "Jean-Pierre Papin", logos: ["france", "om", "milan", "bayern"], tags: ["france","om","milan","bayern","ligue1","seriea","bundesliga","ballondor","striker","retired","hundredgoals"] },
  { id: "ribery", name: "Franck Ribéry", logos: ["france", "om", "bayern"], tags: ["france","om","bayern","ligue1","bundesliga","seriea","midfielder","retired","uclwinner"] },
  { id: "nasri", name: "Samir Nasri", logos: ["france", "om", "arsenal"], tags: ["france","om","arsenal","ligue1","premierleague","midfielder","retired"] },
  { id: "payet", name: "Dimitri Payet", logos: ["france", "om"], tags: ["france","om","ligue1","premierleague","midfielder","retired","hundredgoals"] },
  { id: "benarfa", name: "Hatem Ben Arfa", logos: ["france", "lyon", "om", "psg"], tags: ["france","lyon","om","psg","ligue1","premierleague","midfielder","retired"] },
  { id: "valbuena", name: "Mathieu Valbuena", logos: ["france", "om", "lyon"], tags: ["france","om","lyon","ligue1","midfielder","retired"] },
  { id: "barthez", name: "Fabien Barthez", logos: ["france", "om", "monaco", "manutd"], tags: ["france","worldcupwinner","eurowinner","om","monaco","manutd","ligue1","premierleague","goalkeeper","retired","uclwinner"] },
  { id: "lloris", name: "Hugo Lloris", logos: ["france", "lyon"], tags: ["france","worldcupwinner","lyon","ligue1","premierleague","goalkeeper","active"] },
  { id: "mandanda", name: "Steve Mandanda", logos: ["france", "om"], tags: ["france","worldcupwinner","om","ligue1","premierleague","goalkeeper","active"] },
  { id: "buffon", name: "Gianluigi Buffon", logos: ["italy", "juve", "psg"], tags: ["italy","worldcupwinner","juve","psg","seriea","ligue1","goalkeeper","retired"] },
  { id: "casillas", name: "Iker Casillas", logos: ["spain", "real"], tags: ["spain","worldcupwinner","eurowinner","real","laliga","goalkeeper","retired","uclwinner"] },
  { id: "ramos", name: "Sergio Ramos", logos: ["spain", "real", "psg"], tags: ["spain","worldcupwinner","eurowinner","real","psg","laliga","ligue1","defender","active","hundredgoals","uclwinner"] },
  { id: "puyol", name: "Carles Puyol", logos: ["spain", "barca"], tags: ["spain","worldcupwinner","eurowinner","barca","laliga","defender","retired","uclwinner"] },
  { id: "pique", name: "Gerard Piqué", logos: ["spain", "barca", "manutd"], tags: ["spain","worldcupwinner","eurowinner","barca","manutd","laliga","premierleague","defender","retired","uclwinner"] },
  { id: "maldini", name: "Paolo Maldini", logos: ["italy", "milan"], tags: ["italy","milan","seriea","defender","retired","uclwinner"] },
  { id: "cannavaro", name: "Fabio Cannavaro", logos: ["italy", "real", "juve", "inter"], tags: ["italy","worldcupwinner","ballondor","real","juve","inter","laliga","seriea","defender","retired"] },
  { id: "vandijk", name: "Virgil van Dijk", logos: ["netherlands", "liverpool"], tags: ["netherlands","liverpool","premierleague","defender","active","uclwinner"] },
  { id: "kaka", name: "Kaká", logos: ["brazil", "milan", "real"], tags: ["brazil","worldcupwinner","ballondor","milan","real","seriea","laliga","midfielder","retired","uclwinner"] },
  { id: "modric", name: "Luka Modrić", logos: ["real"], tags: ["ballondor","real","laliga","premierleague","midfielder","active","uclwinner"] },
  { id: "xavi", name: "Xavi", logos: ["spain", "barca"], tags: ["spain","worldcupwinner","eurowinner","barca","laliga","midfielder","retired","uclwinner"] },
  { id: "iniesta", name: "Andrés Iniesta", logos: ["spain", "barca"], tags: ["spain","worldcupwinner","eurowinner","barca","laliga","midfielder","retired","uclwinner"] },
  { id: "pirlo", name: "Andrea Pirlo", logos: ["italy", "milan", "juve", "inter"], tags: ["italy","worldcupwinner","milan","juve","inter","seriea","midfielder","retired","uclwinner"] },
  { id: "seedorf", name: "Clarence Seedorf", logos: ["netherlands", "real", "milan", "inter"], tags: ["netherlands","real","milan","inter","laliga","seriea","midfielder","retired","uclwinner"] },
  { id: "lampard", name: "Frank Lampard", logos: ["chelsea"], tags: ["chelsea","premierleague","midfielder","retired","hundredgoals","uclwinner"] },
  { id: "gerrard", name: "Steven Gerrard", logos: ["liverpool"], tags: ["liverpool","premierleague","midfielder","retired","hundredgoals","uclwinner"] },
  { id: "rooney", name: "Wayne Rooney", logos: ["manutd"], tags: ["manutd","premierleague","striker","retired","hundredgoals","uclwinner"] },
  { id: "shevchenko", name: "Andriy Shevchenko", logos: ["milan", "chelsea"], tags: ["milan","chelsea","seriea","premierleague","ballondor","striker","retired","hundredgoals","uclwinner"] },
  { id: "etoo", name: "Samuel Eto’o", logos: ["africa", "barca", "inter", "chelsea"], tags: ["africa","barca","inter","chelsea","laliga","seriea","premierleague","striker","retired","hundredgoals","uclwinner"] },
  { id: "mane", name: "Sadio Mané", logos: ["africa", "liverpool", "bayern"], tags: ["africa","liverpool","bayern","premierleague","bundesliga","striker","active","uclwinner"] },
  { id: "salah", name: "Mohamed Salah", logos: ["africa", "chelsea", "liverpool"], tags: ["africa","chelsea","liverpool","seriea","premierleague","striker","active","leftfoot","hundredgoals","uclwinner"] },
  { id: "mahrez", name: "Riyad Mahrez", logos: ["africa"], tags: ["africa","premierleague","striker","active","leftfoot","uclwinner"] },
  { id: "auba", name: "Pierre-Emerick Aubameyang", logos: ["africa", "om", "barca", "arsenal", "chelsea", "milan"], tags: ["africa","om","barca","arsenal","chelsea","milan","ligue1","laliga","premierleague","seriea","bundesliga","striker","active","hundredgoals"] },
  { id: "giroud", name: "Olivier Giroud", logos: ["france", "arsenal", "chelsea", "milan"], tags: ["france","worldcupwinner","arsenal","chelsea","milan","ligue1","premierleague","seriea","striker","active","hundredgoals","uclwinner"] },
  { id: "griezmann", name: "Antoine Griezmann", logos: ["france", "barca"], tags: ["france","worldcupwinner","barca","laliga","striker","active","leftfoot","hundredgoals"] },
  { id: "kante", name: "N’Golo Kanté", logos: ["france", "chelsea"], tags: ["france","worldcupwinner","chelsea","ligue1","premierleague","midfielder","active","uclwinner"] },
  { id: "pogba", name: "Paul Pogba", logos: ["france", "manutd", "juve"], tags: ["france","worldcupwinner","manutd","juve","premierleague","seriea","midfielder","active"] },
  { id: "ozil", name: "Mesut Özil", logos: ["germany", "real", "arsenal"], tags: ["germany","worldcupwinner","real","arsenal","laliga","premierleague","bundesliga","midfielder","retired","leftfoot"] },
  { id: "kroos", name: "Toni Kroos", logos: ["germany", "bayern", "real"], tags: ["germany","worldcupwinner","bayern","real","bundesliga","laliga","midfielder","retired","uclwinner"] },
  { id: "muller", name: "Thomas Müller", logos: ["germany", "bayern"], tags: ["germany","worldcupwinner","bayern","bundesliga","midfielder","active","hundredgoals","uclwinner"] },
  { id: "lewandowski", name: "Robert Lewandowski", logos: ["bayern", "barca"], tags: ["bayern","barca","bundesliga","laliga","striker","active","hundredgoals","uclwinner"] },
  { id: "haaland", name: "Erling Haaland", logos: [], tags: ["premierleague","bundesliga","striker","active","leftfoot","hundredgoals","uclwinner"] },
  { id: "debruyne", name: "Kevin De Bruyne", logos: ["chelsea"], tags: ["chelsea","premierleague","bundesliga","midfielder","active","uclwinner"] },
  { id: "hazard", name: "Eden Hazard", logos: ["chelsea", "real"], tags: ["chelsea","real","ligue1","premierleague","laliga","striker","retired","hundredgoals"] },
  { id: "figo", name: "Luís Figo", logos: ["portugal", "barca", "real", "inter"], tags: ["portugal","ballondor","barca","real","inter","laliga","seriea","midfielder","retired","uclwinner"] },
  { id: "deco", name: "Deco", logos: ["portugal", "barca", "chelsea"], tags: ["portugal","barca","chelsea","laliga","premierleague","midfielder","retired","uclwinner"] },
  { id: "suarez", name: "Luis Suárez", logos: ["barca", "liverpool"], tags: ["barca","liverpool","laliga","premierleague","striker","active","leftfoot","hundredgoals","uclwinner"] },
  { id: "aguero", name: "Sergio Agüero", logos: ["argentina", "barca"], tags: ["argentina","barca","laliga","premierleague","striker","retired","hundredgoals"] },
  { id: "tevez", name: "Carlos Tévez", logos: ["argentina", "manutd", "juve"], tags: ["argentina","manutd","juve","premierleague","seriea","striker","retired","hundredgoals","uclwinner"] },
  { id: "dimaria", name: "Ángel Di María", logos: ["argentina", "psg", "real", "juve", "manutd"], tags: ["argentina","worldcupwinner","psg","real","juve","manutd","ligue1","laliga","seriea","premierleague","midfielder","active","leftfoot","uclwinner"] },
  { id: "verratti", name: "Marco Verratti", logos: ["italy", "psg"], tags: ["italy","eurowinner","psg","ligue1","midfielder","active"] },
  { id: "hakimi", name: "Achraf Hakimi", logos: ["africa", "psg", "real", "inter"], tags: ["africa","psg","real","inter","bundesliga","ligue1","laliga","seriea","defender","active"] },
  { id: "marquinhos", name: "Marquinhos", logos: ["brazil", "psg"], tags: ["brazil","psg","ligue1","seriea","defender","active"] },
  { id: "thiagosilva", name: "Thiago Silva", logos: ["brazil", "psg", "milan", "chelsea"], tags: ["brazil","psg","milan","chelsea","ligue1","seriea","premierleague","defender","active","uclwinner"] },
  { id: "osimhen", name: "Victor Osimhen", logos: ["africa"], tags: ["africa","ligue1","seriea","striker","active"] },
  { id: "falcao", name: "Radamel Falcao", logos: ["monaco", "chelsea", "manutd"], tags: ["monaco","chelsea","manutd","ligue1","premierleague","laliga","striker","retired","hundredgoals"] },
  { id: "pauleta", name: "Pauleta", logos: ["portugal", "psg"], tags: ["portugal","psg","ligue1","laliga","striker","retired","hundredgoals"] },
  { id: "cisse", name: "Djibril Cissé", logos: ["france", "om"], tags: ["france","om","ligue1","premierleague","seriea","striker","retired","hundredgoals"] },
  { id: "niang", name: "Mamadou Niang", logos: ["africa", "om"], tags: ["africa","om","ligue1","striker","retired","hundredgoals"] },
  { id: "gignac", name: "André-Pierre Gignac", logos: ["france", "om"], tags: ["france","om","ligue1","striker","active","hundredgoals"] },
  { id: "lacazette", name: "Alexandre Lacazette", logos: ["france", "lyon", "arsenal"], tags: ["france","lyon","arsenal","ligue1","premierleague","striker","active","hundredgoals"] },
  { id: "benyedder", name: "Wissam Ben Yedder", logos: ["france", "monaco"], tags: ["france","monaco","ligue1","laliga","striker","active","hundredgoals"] },
  { id: "balotelli", name: "Mario Balotelli", logos: ["italy", "om", "milan", "inter"], tags: ["italy","om","milan","inter","ligue1","seriea","premierleague","striker","active","hundredgoals","uclwinner"] },
  { id: "depay", name: "Memphis Depay", logos: ["netherlands", "lyon", "barca", "manutd"], tags: ["netherlands","lyon","barca","manutd","ligue1","laliga","premierleague","striker","active","hundredgoals"] }
];
